INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('あ','a','A',1);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('い','i','A',2);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('う','u','A',3);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('え','e','A',4);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('お','o','A',5);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('か','ka','A',6);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('き','ki','A',7);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('く','ku','A',8);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('け','ke','A',9);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('こ','ko','A',10);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('さ','sa','A',11);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('し','si','A',12);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('す','su','A',13);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('せ','se','A',14);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('そ','so','A',15);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('た','ta','A',16);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ち','chi','A',17);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('つ','tsu','A',18);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('て','te','A',19);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('と','to','A',20);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('な','na','A',21);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('に','ni','A',22);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぬ','nu','A',23);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ね','ne','A',24);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('の','no','A',25);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('は','ha','A',26);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ひ','hi','A',27);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ふ','hu','A',28);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('へ','he','A',29);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ほ','ho','A',30);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ま','ma','A',31);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('み','mi','A',32);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('む','mu','A',33);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('め','me','A',34);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('も','mo','A',35);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('や','ya','A',36);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ゆ','yu','A',37);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('よ','yo','A',38);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ら','ra','A',39);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('り','ri','A',40);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('る','ru','A',41);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('れ','re','A',42);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ろ','ro','A',43);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('わ','wa','A',44);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('を','wo','A',45);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ん','n','A',46);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('が','ga','A-1',1);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぎ','gi','A-1',2);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぐ','gu','A-1',3);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('げ','ge','A-1',4);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ご','go','A-1',5);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ざ','za','A-1',6);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('じ','zi','A-1',7);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ず','zu','A-1',8);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぜ','ze','A-1',9);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぞ','zo','A-1',10);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('だ','da','A-1',11);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぢ','di','A-1',12);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('づ','du','A-1',13);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('で','de','A-1',14);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ど','do','A-1',15);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ば','ba','A-1',16);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('び','bi','A-1',17);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぶ','bu','A-1',18);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('べ','be','A-1',19);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぼ','bo','A-1',20);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぱ','pa','A-1',21);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぴ','pi','A-1',22);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぷ','pu','A-1',23);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぺ','pe','A-1',24);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぽ','po','A-1',25);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('きゃ','kya','A-2',1);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('きゅ','kyu','A-2',2);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('きょ','kyo','A-2',3);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('しゃ','sha','A-2',4);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('しゅ','shu','A-2',5);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('しょ','sho','A-2',6);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ちゃ','cha','A-2',7);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ちゅ','chu','A-2',8);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ちょ','cho','A-2',9);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('にゃ','nya','A-2',10);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('にゅ','nyu','A-2',11);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('にょ','nyo','A-2',12);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ひゃ','hya','A-2',13);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ひう','hyu','A-2',14);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ひょ','hyo','A-2',15);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('みゃ','mya','A-2',16);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('みゅ','myu','A-2',17);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('みょ','myo','A-2',18);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('りゃ','rya','A-2',19);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('りゅ','ryu','A-2',20);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('りょ','ryo','A-2',21);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぎゃ','gya','A-3',1);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぎゅ','gyu','A-3',2);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぎょ','gyo','A-3',3);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('じゃ','ja','A-3',4);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('じゅ','ju','A-3',5);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('じょ','jo','A-3',6);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぢゃ','dya','A-3',7);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぢゅ','dyu','A-3',8);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぢょ','dyo','A-3',9);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('びゃ','bya','A-3',10);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('びゅ','byu','A-3',11);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('びょ','byo','A-3',12);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぴゃ','pya','A-3',13);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぴゅ','pyu','A-3',14);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ぴょ','pyo','A-3',15);

----------------------------------------------------------------------------

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ア','a','B',1);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('イ','i','B',2);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ウ','u','B',3);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('エ','e','B',4);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('オ','o','B',5);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('カ','ka','B',6);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('キ','ki','B',7);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ク','ku','B',8);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ケ','ke','B',9);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('コ','ko','B',10);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('サ','sa','B',11);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('シ','si','B',12);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ス','su','B',13);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('セ','se','B',14);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ソ','so','B',15);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('タ','ta','B',16);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('チ','ti','B',17);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ツ','tu','B',18);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('テ','te','B',19);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ト','to','B',20);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ナ','na','B',21);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ニ','ni','B',22);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヌ','nu','B',23);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ネ','ne','B',24);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ノ','no','B',25);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ハ','ha','B',26);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヒ','hi','B',27);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('フ','hu','B',28);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヘ','he','B',29);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ホ','ho','B',30);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('マ','ma','B',31);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ミ','mi','B',32);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ム','mu','B',33);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('メ','me','B',34);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('モ','mo','B',35);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヤ','ya','B',36);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ユ','yu','B',37);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヨ','yo','B',38);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ラ','ra','B',39);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('リ','ri','B',40);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ル','ru','B',41);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('レ','re','B',42);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ロ','ro','B',43);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ワ','wa','B',44);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヲ','wo','B',45);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ン','n','B',46);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ガ','ga','B-1',1);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ギ','gi','B-1',2);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('グ','gu','B-1',3);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ゲ','ge','B-1',4);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ゴ','go','B-1',5);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ザ','za','B-1',6);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ジ','zi','B-1',7);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ズ','zu','B-1',8);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ゼ','ze','B-1',9);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ゾ','zo','B-1',10);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ダ','da','B-1',11);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヂ','di','B-1',12);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヅ','du','B-1',13);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('デ','de','B-1',14);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ド','do','B-1',15);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('バ','ba','B-1',16);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ビ','bi','B-1',17);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ブ','bu','B-1',18);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ベ','be','B-1',19);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ボ','bo','B-1',20);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('パ','pa','B-1',21);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ピ','pi','B-1',22);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('プ','pu','B-1',23);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ペ','pe','B-1',24);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ポ','po','B-1',25);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('キャ','kya','B-2',1);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('キュ','kyu','B-2',2);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('キョ','kyo','B-2',3);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('シャ','sha','B-2',4);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('シュ','shu','B-2',5);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ショ','sho','B-2',6);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('チャ','cha','B-2',7);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('チュ','chu','B-2',8);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('チョ','cho','B-2',9);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ニャ','nya','B-2',10);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ニュ','nyu','B-2',11);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ニョ','nyo','B-2',12);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヒャ','hya','B-2',13);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヒュ','hyu','B-2',14);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヒョ','hyo','B-2',15);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ミャ','mya','B-2',16);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ミュ','myu','B-2',17);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ミョ','myo','B-2',18);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('リャ','rya','B-2',19);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('リュ','ryu','B-2',20);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('リョ','ryo','B-2',21);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ギャ','gya','B-3',1);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ギュ','gyu','B-3',2);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ギョ','gyo','B-3',3);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ジャ','ja','B-3',4);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ジュ','ju','B-3',5);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ジョ','jo','B-3',6);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヂャ','dya','B-3',7);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヂュ','dyu','B-3',8);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ヂョ','dyo','B-3',9);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ビャ','bya','B-3',10);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ビュ','byu','B-3',11);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ビョ','byo','B-3',12);

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ピャ','pya','B-3',13);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ピュ','pyu','B-3',14);
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY, SORT) VALUES('ピョ','pyo','B-3',15);