INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('あ','a','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('い','i','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('う','u','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('え','e','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('お','o','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('か','ka','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('き','ki','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('く','ku','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('け','ke','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('こ','ko','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('さ','sa','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('し','si','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('す','su','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('せ','se','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('そ','so','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('た','ta','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ち','ti','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('つ','tu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('て','te','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('と','to','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('な','na','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('に','ni','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぬ','nu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ね','ne','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('の','no','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('は','ha','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ひ','hi','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ふ','hu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('へ','he','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ほ','ho','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ま','ma','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('み','mi','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('む','mu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('め','me','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('も','mo','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('や','ya','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ゆ','yu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('よ','yo','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ら','ra','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('り','ri','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('る','ru','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('れ','re','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ろ','ro','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('わ','wa','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('を','wo','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ん','n','A');