INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('あ','a','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('い','i','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('う','u','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('え','e','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('お','o','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('か','ka','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('き','ki','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('く','ku','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('け','ke','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('こ','ko','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('さ','sa','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('し','si','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('す','su','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('せ','se','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('そ','so','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('た','ta','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ち','ti','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('つ','tu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('て','te','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('と','to','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('な','na','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('に','ni','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぬ','nu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ね','ne','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('の','no','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('は','ha','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ひ','hi','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ふ','hu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('へ','he','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ほ','ho','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ま','ma','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('み','mi','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('む','mu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('め','me','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('も','mo','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('や','ya','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ゆ','yu','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('よ','yo','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ら','ra','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('り','ri','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('る','ru','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('れ','re','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ろ','ro','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('わ','wa','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('を','wo','A');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ん','n','A');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('が','ga','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぎ','gi','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぐ','gu','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('げ','ge','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ご','go','A-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ざ','za','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('じ','zi','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ず','zu','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぜ','ze','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぞ','zo','A-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('だ','da','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぢ','di','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('づ','du','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('で','de','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ど','do','A-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ば','ba','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('び','bi','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぶ','bu','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('べ','be','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぼ','bo','A-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぱ','pa','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぴ','pi','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぷ','pu','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぺ','pe','A-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぽ','po','A-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('きゃ','kya','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('きゅ','kyu','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('きょ','kyo','A-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('しゃ','sha','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('しゅ','shu','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('しょ','sho','A-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ちゃ','cha','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ちゅ','chu','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ちょ','cho','A-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('にゃ','nya','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('にゅ','nyu','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('にょ','nyo','A-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ひゃ','hya','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ひう','hyu','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ひょ','hyo','A-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('みゃ','mya','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('みゅ','myu','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('みょ','myo','A-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('りゃ','rya','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('りゅ','ryu','A-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('りょ','ryo','A-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぎゃ','gya','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぎゅ','gyu','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぎょ','gyo','A-3');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('じゃ','ja','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('じゅ','ju','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('じょ','jo','A-3');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぢゃ','dya','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぢゅ','dyu','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぢょ','dyo','A-3');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('びゃ','bya','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('びゅ','byu','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('びょ','byo','A-3');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぴゃ','pya','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぴゅ','pyu','A-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ぴょ','pyo','A-3');

----------------------------------------------------------------------------

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ア','a','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('イ','i','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ウ','u','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('エ','e','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('オ','o','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('カ','ka','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('キ','ki','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ク','ku','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ケ','ke','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('コ','ko','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('サ','sa','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('シ','si','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ス','su','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('セ','se','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ソ','so','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('タ','ta','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('チ','ti','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ツ','tu','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('テ','te','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ト','to','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ナ','na','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ニ','ni','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヌ','nu','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ネ','ne','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ノ','no','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ハ','ha','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヒ','hi','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('フ','hu','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヘ','he','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ホ','ho','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('マ','ma','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ミ','mi','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ム','mu','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('メ','me','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('モ','mo','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヤ','ya','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ユ','yu','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヨ','yo','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ラ','ra','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('リ','ri','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ル','ru','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('レ','re','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ロ','ro','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ワ','wa','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヲ','wo','B');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ン','n','B');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ガ','ga','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ギ','gi','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('グ','gu','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ゲ','ge','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ゴ','go','B-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ザ','za','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ジ','zi','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ズ','zu','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ゼ','ze','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ゾ','zo','B-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ダ','da','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヂ','di','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヅ','du','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('デ','de','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ド','do','B-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('バ','ba','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ビ','bi','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ブ','bu','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ベ','be','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ボ','bo','B-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('パ','pa','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ピ','pi','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('プ','pu','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ペ','pe','B-1');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ポ','po','B-1');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('キャ','kya','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('キュ','kyu','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('キョ','kyo','B-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('シャ','sha','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('シュ','shu','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ショ','sho','B-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('チャ','cha','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('チュ','chu','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('チョ','cho','B-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ニャ','nya','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ニュ','nyu','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ニョ','nyo','B-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヒャ','hya','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヒュ','hyu','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヒョ','hyo','B-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ミャ','mya','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ミュ','myu','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ミョ','myo','B-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('リャ','rya','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('リュ','ryu','B-2');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('リョ','ryo','B-2');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ギャ','gya','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ギュ','gyu','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ギョ','gyo','B-3');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ジャ','ja','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ジュ','ju','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ジョ','jo','B-3');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヂャ','dya','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヂュ','dyu','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ヂョ','dyo','B-3');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ビャ','bya','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ビュ','byu','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ビョ','byo','B-3');

INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ピャ','pya','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ピュ','pyu','B-3');
INSERT INTO TB_ALPHABET(JAPANESE, ROMA, CATEGORY) VALUES('ピョ','pyo','B-3');